jadwal/urls.py
from django.urls import path
from . import views

app_name = 'sched'

urlpatterns = [
    path('', views.schedule, name='schedule'),
    path('delete/<int:id>', views.delete, name='deletesched')
    # dilanjutkan ...
]

projectstory5/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jadwal.urls') )
]

jadwal/models.py
from django.db import models

# Create your models here.
class Sched(models.Model):
    name = models.CharField(max_length = 50)
    tempat = models.CharField(max_length = 50)
    kategori = models.CharField(max_length = 50)
    tanggal = models.DateField()
    waktu = models.TimeField()

jadwal/forms.py
from django import forms

class ScheduleForm(forms.Form):
    name = forms.CharField(max_length = 50)
    tempat = forms.CharField(max_length = 50)
    tanggal = forms.DateField()
    waktu = forms.TimeField()
    kategori = forms.CharField(max_length = 50)

jadwal/views.py
from django.shortcuts import render
from .forms import ScheduleForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Sched

# Create your views here.

def schedule(request):
    if request.method == 'POST':
        form = ScheduleForm(request.POST)

        if form.is_valid():
            nama = form.cleaned_data['name']
            place = form.cleaned_data['tempat']
            date = form.cleaned_data['tanggal']
            time = form.cleaned_data['waktu']
            category = form.cleaned_data['kategori']

            jadwal = Sched(name = nama , tempat = place , tanggal = date, waktu = time,kategori = category )
            jadwal.save()

            return HttpResponseRedirect(reverse('sched:schedule'))
        else:
            schedules = Sched.objects.all()
            context = {
                'sched' : form,
                'jadwalbaru' : schedules
            }
            return render(request,'schedule.html',context)


    schedules = Sched.objects.all()
    print(schedules)
    form = ScheduleForm()
    context =  {
        'sched': form,
        'jadwalbaru' : schedules,
    }
    return render(request,'schedule.html',context)

def delete(request, id):
    Sched.objects.get(pk = id).delete()
    return HttpResponseRedirect(reverse('sched:schedule'))

jadwal/templates/schedule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    <form action = "{% url 'sched:schedule' %}" method="POST">
        {% csrf_token %}
        {{sched}}
    <input type="submit" value="Submit" />
    </form>
    <br>
    <br>
    <table style="margin: 20px">
        <tbody>
        {% for jadwal in jadwalbaru %}
        <tr style="margin: 30px">
            <td style="padding: 30px"> {{jadwal.name}} </td>
            <td style ="padding: 30px"> {{jadwal.tempat}}</td>
            <td style ="padding: 30px">{{jadwal.kategori}} </td>
            <td style ="padding: 30px">{{jadwal.tanggal}}</td>
            <td style ="padding: 30px">{{jadwal.waktu}}</td>
            <td><a href = "{% url 'sched:deletesched' jadwal.id %}">Delete cuy</a></td>
        </tr>
    
        
        {% endfor %}
        </tbody>    
    </table>
    
</body>
</html>